### ISSUE TITLE
No more contrast control on scans when using 3D Plot options in viewer

### ISSUE THREAD

**Issue by adelphin** [nifm-gin/MP3#10]
**Describe the bug**
When loading more than 2 scans and a ROI, it is convenient to have a control on the 3D plot on the right of the viewer. However, if right-click > "activate 3D view" does the work, it removes the control on the contrast of the scans (middle and right-click). There is no way to de-activate the 3D view other than closing and re-opening MP3.

**To Reproduce**
1. Load a database
2. Load 1 or more scans
3. Load a ROI
4. Right-click > Activate 3d view on the plot on the right side of the viewer
5. Have control of the plot, but no more control on the contrast of the scans

**Expected behavior**
Having the possibility to switch from to the other without closing MP3 would be good. The best would be to have both control on the contrast and the 3d plot. 

**Desktop:**
 - Ubuntu 18.04
 - Matlab R2018a

**Comment by brosscle** [comment]
Hi Aurélien,
Thanks for challenging MP3 !
That's an issue we haven't faced yet.
A quick internet research makes me pessimist as there is maybe no elegant solution to exit this matlab mode : https://fr.mathworks.com/matlabcentral/answers/97199-how-can-i-toggle-rotate3d-mode-in-a-gui-depending-on-whether-the-mouse-cursor-is-inside-or-outside
However, when 3D plot is activate, you can toggle it off by clicking on one of graphical icons of the toolbar menu to toggle it on and then immediately switch it off (ie double click on it). It will exit from the 3D matlab mode.
Of course this isn't a viable solution but for now it will fix your issue.
We will investigate this new issue as soon as possible.
Hope this helps !
Clément

**Comment by adelphin** [comment]
Great, thank you for the quick solution!
