### ISSUE TITLE
Auto-save when importing from another MP3 database

### ISSUE THREAD

**Issue by adelphin** [nifm-gin/MP3#11]
When using the feature "Import data from another database", the "Done" window opens but the database is not saved, and it is easy to forget to manually save it. As a result the files are imported but the database.mat remains empty, the project can't be re-opened and the importation time is lost.

Auto-saving the database at the end of importation would be nice.

**Comment by brosscle** [comment]
Hi Aurélien,
Thanks for this reporting.
This issue is solved, the database is now automatically saved after the importation of data from another MP3 project. I pushed the modification on the dev branch but also merged the dev branch into the master one.
Thanks again !
