### ISSUE TITLE
Wrong group's name when adding new data to a patient

### ISSUE THREAD

**Issue by blemasso** [nifm-gin/MP3#14]
**_steps to reproduce the bug_**
First I change the name of the group for one patient. Let says the new group's name is "treated".
If I add another scan to this patient, this scan will have "Undefined" as group's name instead of "treated"

**Comment by brosscle** [comment]
How is the new scan added ? From an importation, a "copy to another session", a pipeline execution, ... ?

**Comment by blemasso** [comment]
from "import data" --> 'import raw data"

**Comment by brosscle** [comment]
Ok I fixed the issue.
Now the group of the new scan is the same that the one of the scans of the same Patient and timepoint.
If there is several group names among the scans belonging to the same Patient / Timepoint, the first group name is chosen (in alphabetically order)

**Comment by blemasso** [comment]
perfect! tks
