### ISSUE TITLE
Impossibility to use without parallel toolbox

### ISSUE THREAD

**Issue by dgrens** [nifm-gin/MP3#18]
**Describe the bug**
Impossible to launch a pipeline if the parallel toolbox is missing

**Desktop (please complete the following information):**
all systems and desktop

**Comment by blemasso** [comment]
Hi,

Thank you for the feedback.
Could you post the error message so we can propose a solution?

best,
Benjamin

**Comment by blemasso** [comment]
an attempt to fix this bug bug is proposed on the "dev" branch 
https://github.com/nifm-gin/MP3/commit/61059cc07d078ff10a081734846b82d1b1c1d1af

Can you try it? If it works, I can push this fix to the Master
