### ISSUE TITLE
export from convertor failed

### ISSUE THREAD

**Issue by eckuijper** [nifm-gin/MP3#19]
I am experiencing some problems with importing several of the scans. Most of the scans are correctly converted from Bruker files to Nifti+JSON files, but for our T2 TurboRARE high resolution files, I get a message that the export failed with an error such as this:

java.lang.NumberFormatException: For input string: "@15*(1)"
 
I am working in Windows 10, using Matlab R2020b and MRI Files Manager 20.2.2a.

**Comment by blemasso** [comment]
Hi,

Thank you for your feedback.
We will try to solve your problem asap.
Could you send us at least a single dataset via a dropbox link (or other)?

thank you,
Benjamin

**Comment by blemasso** [comment]
Hi,
thank you for the dataset.
I have the same issue on my side. I also observed an error in the conversion of perfusion_FAIR_EPI sequence (there is a mix of images between the 5 dimensions).
I will ask the developer of this import software to work on it.

@montigno could you please have a look to this data. There are 2 conversions problems 
   1) for the T2 TurboRARE high resolution (no conversion at all)
   2) for the perfusion_FAIR_EPI (there is one conversion but images are mixed).
you will be able to find the data here: https://filesender.renater.fr/?s=download&token=b46ace1b-0833-4889-839e-ec4bb59de15d 

We will get back to you asap.

best,

**Comment by eckuijper** [comment]
Thank you!

**Comment by montigno** [comment]
Hi,

mri_conv is compatible with Paravision 5 and 6, not with Paravision 360 but i am modifying the code to make it compatible, i think it will not take much time.

I'll keep you informed

best,

Olivier M.

**Comment by eckuijper** [comment]
Hi Olivier, 

Great, thank you! 

Best,
Elsa

**Comment by montigno** [comment]
Hi,

I put a new version of mri_conv in the 'dev' branch, it is compatible with Paravision360 but other bugs may appear.
I let Benjamin put the software in the master branch.

Best,

Olivier

**Comment by blemasso** [comment]
Hi,

we have to test this code before to merge it to the master.
But @eckuijper, you can download the branch 'dev' here: https://github.com/nifm-gin/MP3/tree/dev

Let us know if it works.

best,
Benjamin

**Comment by eckuijper** [comment]
Dear Benjamin and Oliver,

Thank you very much! The conversion of the raw data works now, the issue with the T2 TurboRARE high resolution and perfusion_FAIR_EPI scans is solved. 
However, we experience a problem with the conversion of the parameter maps of the T2star MGE scans, these are now not correctly loaded (example image attached). Have you seen this problem before? 

Kind regards,
Elsa

![t2star_signal intensity](https://user-images.githubusercontent.com/82893372/117988995-3bf12080-b33c-11eb-9ef1-3d482c2c255e.PNG)

**Comment by montigno** [comment]
Dear Elsa,

I solved the problem but I have to see with Benjamin for the intensity of the image, it seems high to me but it is perhaps normal.
We keep you informed.

Best regards,

Olivier

**Comment by montigno** [comment]
Dear Elsa,

I put a new version of mri_conv (21.6.1a) in the 'dev' branch (I solved the intensity problem).
You can download it here: https://github.com/nifm-gin/MP3/tree/dev.

Best,

Olivier

**Comment by eckuijper** [comment]
Dear Olivier,

Great, thank you! I will download and try it!

Best,
Elsa

**Comment by eckuijper** [comment]
Dear Olivier,

I just checked the upload of the T2star parameter maps and the problem is indeed solved :) Thank you!

Best,
Elsa
