### ISSUE TITLE
Matlab error when using Module_DCE_phenomeno

### ISSUE THREAD

**Issue by rbolbos** [nifm-gin/MP3#23]
**Describe the bug**

Matlab error when using Module_DCE_phenomeno.

**To Reproduce**

1. File, Import Data, Import Raw Data => OK
2. MP3 pipeline Manager => OK
3. Module_DCE_phenomeno.m selection => OK, **BUT** :  "End of the analysis (in sec)" is displayed as "180", although the "180" is the total number of T1 images (9 slices with 20 repetitions). 

**Expected behavior**

I am performing a DCE experiment on an IN VIVO mouse brain using a T1w sequence : 9 slices, TR : 350ms, 20 repetitions.
The acquisition time of a single T1w scan is 1m29s600ms, so the total scan time for 20 repetitions is 29m52s.

Experiment TIMELINE : 4 baseline repetitions + Gadolinium injection + 16 dynamic repetitions. 

I expect to obtain different output files / images : AUC, Pax, TTP, pc_enhanc ...

**Screenshots**

Here are the MATLAB errors that I obrain after executing the pipeline : 

_no parallel-computing toolbox installed. Number of worker = 1
Your pipeline (1 jobs) will be executed in Basic Loop :
Execution Job 1

Error using  - 
Matrix dimensions must agree.

Error in Module_DCE_phenomeno (line 212)
    [~, fin] = min(abs(repetion_time -(debut*TR + opt.End_analysis)));

Error in MP3_pipeline>MP3_pipeline_execute_button_Callback (line 2434)
        eval(Module.command);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in MP3_pipeline (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)MP3_pipeline('MP3_pipeline_execute_button_Callback',hObject,eventdata,guidata(hObject))
Error while evaluating UIControl Callback._

**Desktop (please complete the following information):**

 - OS: LINUX CentOS 7
 - MATLAB version 2018a

**Comment by blemasso** [comment]
Dear Radu

From what I've observed, there seems to be a problem with your data. In fact, there is a saturation of the signal shortly after the injection of the contrast agent. This saturation causes an error in the code, as it is not possible to automatically detect the bolus of a saturated curve. 
However, by attempting a manual analysis of your data, I was able to uncover an unexpected error that has now been fixed.
I recommend that you update MP3 and test with the manual bolus detection parameters. 
     last dyn before bolus --> 4
     end of analysis (in sec) -> 300 

With these parameters you should get permeability maps
