### ISSUE TITLE
issue with spm_slice_vol

### ISSUE THREAD

**Issue by blemasso** [nifm-gin/MP3#4]
**Describe the bug**
Contrary to niftiread (from Matlab) spm_slice_vol (used through the read_volume function) does not use the nifti type when loading the data. Therefore, even if the nifti is an 'int16', the data will be loaded as a double.
--> consequence : data space may be multiply by 4

It is especially hassle in Module_Arithmetic or Module_Texture_matlab (and maybe others) because the nifti generated are saved in double instead of 'int16'

**Comment by brosscle** [comment]
Currently working on this enhancement in the DataTypeHandling branch.

**Comment by brosscle** [comment]
The branch DataTypeHandling is now merged into the dev branch.
Feel free to test its behavior and to report any issue !

**Comment by brosscle** [comment]
The branch dev has been merged into the master branch when launching the release 1.2.
I guess this issue is then resolved.
Please report any issue you may encounter !
