### ISSUE TITLE
AIF using ROI for Susceptibility module

### ISSUE THREAD

**Issue by GaetanDavout** [nifm-gin/MP3#5]
**Is your feature request related to a problem? Please describe.**
searching automatically an AIF in DSC images isn't worth when it comes to primate.

**Describe the solution you'd like**
A solution would be to add a manual way of choosing AIF with a VOI.

**Describe alternatives you've considered**
I haven't considered any other alternative.

**Additional context**

**Comment by blemasso** [comment]
I modify the module (the module is now called module_DSC.m)
could you test it and give me your feedback?

**Comment by GaetanDavout** [comment]
It seems to work very well!
I just wonder if that is normal that it takes more than one hour to perform this function?
(It may be caused by my setup...)

**Comment by blemasso** [comment]
ok nice,
One hour seems little bit long but not far out. You can use the option "Remove background" to accelerate the processing.
Depending of the number of CPU on your computer, you will be able to run several DSC in parallel using the PSOM mode.

**Comment by GaetanDavout** [comment]
thanks for the advice!
It works within 40mn without the background.
