### ISSUE TITLE
movefile error when importing raw data on SUMOONE

### ISSUE THREAD

**Issue by adelphin** [nifm-gin/MP3#9]
**Describe the bug**
When importing Bruker data with MRI_conv toward Raw_data on SUMOONE shared project, Matlab crashed when performing the movefile from tmp to Raw_data, even if the user has rw rights.
Commenting the movefile lines (MP3.m lines 4538 & 4539) and replacing them by:
> src=fullfile(MP3_tmp_folder, [NAME, '.nii']);
> dest=[char(handles.database.Path(end)), char(handles.database.Filename(end)), '.nii'];
> cmd = ['mv ' src ' ' dest]; 
> system(cmd);
> src=fullfile(MP3_tmp_folder, [NAME, '.json']);
> dest=[char(handles.database.Path(end)), char(handles.database.Filename(end)), '.json'];
> cmd = ['mv ' src ' ' dest]; 
> system(cmd);

Same thing happens when renaming a sequence, as movefile is used.

**To Reproduce**
1. Load the common project on SUMOONE
2. Import bruker data using MRI_conv (e.g. import a raw scan from any animal)
3. Importation works and the scan is stored in tmp/
4. Enter animal ID and time point
5. Observe the red lines stating that "movefile failed: permission denied"
> Cannot write to destination: /home_ldap/_PROJECTS/Preclinical_Database/IRM/Raw_data.  > Use the 'f' option to override.

(However, 'f' option does not solve the problem)

**Expected behavior**
The movefile should work as the user has the rights. Using a mv in a terminal works.

**Desktop (please complete the following information):**
 - OS: CentOS (HYPNOS computer)

**Comment by brosscle** [comment]
Hi Aurelien,
Thanks for this issue report and for this modification!
We will investigate this exception as soon as possible.
